"""empty message

Revision ID: 200d7f29bfa0
Revises: fd73a559361f
Create Date: 2023-10-09 23:41:20.586529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '200d7f29bfa0'
down_revision: Union[str, None] = 'fd73a559361f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gameattribute', 'is_main',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gameattribute', 'is_main',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
