"""empty message

Revision ID: 559cb08be852
Revises: 200d7f29bfa0
Create Date: 2023-10-10 13:34:39.809391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '559cb08be852'
down_revision: Union[str, None] = '200d7f29bfa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'is_deleted')
    # ### end Alembic commands ###
