"""Bonus game +

Revision ID: b74e7703c559
Revises: 83c72ddcc7d7
Create Date: 2023-10-30 02:14:11.860426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b74e7703c559'
down_revision: Union[str, None] = '83c72ddcc7d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('has_bonus_game', sa.Boolean(), nullable=True))
    op.add_column('book', sa.Column('bonus_game_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'bonus_game_id')
    op.drop_column('book', 'has_bonus_game')
    # ### end Alembic commands ###
