"""Add Basket

Revision ID: cce20988af3f
Revises: 655ea318e16b
Create Date: 2023-10-30 00:16:36.286126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cce20988af3f'
down_revision: Union[str, None] = '655ea318e16b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basket',
    sa.Column('user_uuid', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('basketitem',
    sa.Column('basket_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['basket_id'], ['basket.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('book', sa.Column('start_date', sa.DateTime(), nullable=False))
    op.add_column('book', sa.Column('end_date', sa.DateTime(), nullable=False))
    op.add_column('book', sa.Column('client_email', sa.String(), nullable=False))
    op.drop_column('book', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('book', 'client_email')
    op.drop_column('book', 'end_date')
    op.drop_column('book', 'start_date')
    op.drop_table('basketitem')
    op.drop_table('basket')
    # ### end Alembic commands ###
