"""Add total_hours to Book

Revision ID: 11be39e6f898
Revises: b1493997277f
Create Date: 2024-01-24 17:24:57.784729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11be39e6f898'
down_revision: Union[str, None] = 'b1493997277f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('total_hours', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'total_hours')
    # ### end Alembic commands ###
