"""Add legal_id into book, sales_count to Game

Revision ID: 2d4d8d09b7b5
Revises: 5598c21444f0
Create Date: 2023-10-24 19:21:48.813432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d4d8d09b7b5'
down_revision: Union[str, None] = '5598c21444f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('legal_id', sa.String(length=11), nullable=False))
    op.add_column('game', sa.Column('sales_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'sales_count')
    op.drop_column('book', 'legal_id')
    # ### end Alembic commands ###
