"""empty message

Revision ID: 39ecb8903175
Revises: 2af90e8617e1
Create Date: 2023-12-12 21:43:31.942446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39ecb8903175'
down_revision: Union[str, None] = '2af90e8617e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'payment_method')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('payment_method', sa.VARCHAR(), server_default=sa.text("'card'::character varying"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
