"""27112023_2

Revision ID: 5321e64d4257
Revises: c40dd92b4614
Create Date: 2023-11-27 19:50:12.430625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5321e64d4257'
down_revision: Union[str, None] = 'c40dd92b4614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'user_uuid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('book', 'delivery_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'delivery_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('book', 'user_uuid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
