"""Bonus game +

Revision ID: 60d28428631a
Revises: c949b14c5bd3
Create Date: 2023-10-30 02:45:42.632393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60d28428631a'
down_revision: Union[str, None] = 'c949b14c5bd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('test_field', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'test_field')
    # ### end Alembic commands ###
