"""Ticket 20

Revision ID: 655ea318e16b
Revises: 2d4d8d09b7b5
Create Date: 2023-10-26 20:21:20.259377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '655ea318e16b'
down_revision: Union[str, None] = '2d4d8d09b7b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gametobook',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('game_price_before', sa.Float(), nullable=False),
    sa.Column('game_price_after', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('book', sa.Column('has_manager', sa.Boolean(), nullable=True))
    op.add_column('book', sa.Column('managers_count', sa.Integer(), nullable=True))
    op.add_column('book', sa.Column('total_price', sa.Float(), nullable=False))
    op.drop_constraint('book_game_id_fkey', 'book', type_='foreignkey')
    op.drop_column('book', 'game_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('book_game_id_fkey', 'book', 'game', ['game_id'], ['id'])
    op.drop_column('book', 'total_price')
    op.drop_column('book', 'managers_count')
    op.drop_column('book', 'has_manager')
    op.drop_table('gametobook')
    # ### end Alembic commands ###
