"""empty message

Revision ID: a36dd333fe65
Revises: 5321e64d4257
Create Date: 2023-12-11 13:23:28.075977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a36dd333fe65'
down_revision: Union[str, None] = '5321e64d4257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('is_delivered', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('book', sa.Column('payment_method', sa.String(), server_default='card', nullable=False))
    op.add_column('book', sa.Column('is_prepayment', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('book', sa.Column('prepayment_done', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'prepayment_done')
    op.drop_column('book', 'is_prepayment')
    op.drop_column('book', 'payment_method')
    op.drop_table('message')
    # ### end Alembic commands ###
