"""Init

Revision ID: aae33552fe2b
Revises: 2efea08cb4da
Create Date: 2023-11-13 03:14:47.615383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aae33552fe2b'
down_revision: Union[str, None] = '2efea08cb4da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gameattribute', 'icon')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gameattribute', sa.Column('icon', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
