"""empty message

Revision ID: b1493997277f
Revises: 39ecb8903175
Create Date: 2023-12-12 21:44:45.976945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'b1493997277f'
down_revision: Union[str, None] = '39ecb8903175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    payment_method_enum = postgresql.ENUM('prepayment', 'card', name='paymentmethod', create_type=False)
    payment_method_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('book', sa.Column('payment_method', payment_method_enum, server_default='card', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'payment_method')
    # ### end Alembic commands ###
