"""27112023

Revision ID: c40dd92b4614
Revises: c7a7f6422e87
Create Date: 2023-11-27 19:48:52.192128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c40dd92b4614'
down_revision: Union[str, None] = 'c7a7f6422e87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('user_uuid', sa.String(), nullable=True))
    op.add_column('book', sa.Column('delivery_address', sa.String(), nullable=True))
    op.add_column('book', sa.Column('extra', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'extra')
    op.drop_column('book', 'delivery_address')
    op.drop_column('book', 'user_uuid')
    # ### end Alembic commands ###
