import requests
from requests.auth import HTTPBasicAuth

PP_CLIENT_TEST_ID = 'AVcUxSz9mUf9swLQEkQfa8IYqK5ZZ2qEYfCiBje85_5Om8TiniQ3oAt3qd4K1v_UuuXGXpaEFFcJ0M0j'
PP_CLIENT_TEST_SECRET = 'ECRGDFdiKAqbZn8zghyhMHTJMJQo1zzLz8_k--BML8TjUMoPAIMQ3hzJhx7ukmw1nkwSzHnQTszpd98G'
